### PR TITLE
Fix regressions

### PR DESCRIPTION
**Pull request by boulund**
I'm very sorry, but I totally missed these minor regressions in my reformatting. I hope you can merge the fixes quickly so we can update the bioconda recipe asap! :)

### CODE REVIEW

**Review by metageni — APPROVED** [review]
Sorry. I just saw it.

**Comment by metageni** [comment]
@boulund LGTM

**Comment by boulund** [comment]
Thanks! As soon as you create a new release I will update the bioconda package as well.

**Comment by metageni** [comment]
Done @boulund

**Comment by metageni** [comment]
Thank you for all the time you put on it

**Pull request merged**
